dist: trusty
sudo: required
language: rust
rust:
  - stable
  - beta
  - nightly
before_install:
  - curl https://download.ceph.com/keys/release.asc | sudo apt-key add -
  - sudo apt-add-repository 'deb https://download.ceph.com/debian-luminous/ trusty main'
  - sudo apt-get -qq update
  - sudo apt-get install librados-dev
